### ISSUE TITLE
New release of cookbook...

### ISSUE THREAD

**Issue by snkutlu** [elijah/chef-prometheus#46]
Hi 

Do you have any date planned for the new release? There is 0.6.0 version in the repo but latest release was 0.5.1.

Thanks and regards.
-Suleyman Kutlu

**Comment by lamont** [comment]
Bumping the request. I'm doing some work with prometheus now and I'd like to update it to 0.18 version and take some of the config changes into account. There seem to be a lot of lingering pull requests, is this cookbook still going to receive attention from @rayrod2030? I'm happy to do the work, just want to make sure it's in line with whatever you had in mind.

**Comment by elijah** [comment]
Going to close this issue; I'd like to get the source builds fixed and then release a new rev / upload to supermarket.  I'm trying to close a bunch of pending work off, because several folks are *very* interested in picking up and running with this cookbook again.  Integrated support (version number bump and shasum for the binary...) for the most recent non-2.0 build earlier; maybe the thing to do is run the next major cookbook bump with 2.0 when it releases.
